### ISSUE TITLE
KARGA has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by christophevandijck** [DataIntellSystLab/KARGA#1]
Hi,
I wanted to try out your tool, but I ran into the following issue after typing the command `java KARGA example.fastq`:

`Error: LinkageError occurred while loading main class KARGA
	java.lang.UnsupportedClassVersionError: KARGA has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

Indeed, I am unable to update Java to a more recent version than 11.0.1 on our server as I do not have sudo rights.
I am not so experienced with Java, but I wonder if this issue might be solved if you could, by any possibility, provide class files that are compiled with an older version of Java?

Thank you very much in advance.

**Comment by DataIntellSystLab** [comment]
Hi,
I’ll see if we can compile the source on Java version <=11 and get back to you.

Sent from my iPhone

On Nov 16, 2021, at 10:48 AM, christophevandijck ***@***.***> wrote:

﻿
[External Email]

Hi,
I wanted to try out your tool, but I ran into the following issue after typing the command java KARGA example.fastq:

Error: LinkageError occurred while loading main class KARGA java.lang.UnsupportedClassVersionError: KARGA has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Indeed, I am unable to update Java to a more recent version than 11.0.1 on our server as I do not have sudo rights.
I am not so experienced with Java, but I wonder if this issue might be solved if you could, by any possibility, provide class files that are compiled with an older version of Java?

Thank you very much in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DataIntellSystLab_KARGA_issues_1&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=JwuJ1w2SX8Eq7z2G1vWDTt3xQ39YeafDqhIF06JiDng&m=Pbwy-wH-T_c2Tc6fechV-n_WjtG5BCQS6AMW6yBOmY1xL2j2hUsGPFFF5agA84Q5&s=JotPB9f5gbgYc63FelEj730N9_hHvLN8d8d1n9I6SVk&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOFR5ODBF4FYASABDCIWYSDUMJ4H5ANCNFSM5IETGHZQ&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=JwuJ1w2SX8Eq7z2G1vWDTt3xQ39YeafDqhIF06JiDng&m=Pbwy-wH-T_c2Tc6fechV-n_WjtG5BCQS6AMW6yBOmY1xL2j2hUsGPFFF5agA84Q5&s=EeKbJ_3WEspfeLEWl5cc55DB1zWGMYNRuhiUko6f-cY&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=JwuJ1w2SX8Eq7z2G1vWDTt3xQ39YeafDqhIF06JiDng&m=Pbwy-wH-T_c2Tc6fechV-n_WjtG5BCQS6AMW6yBOmY1xL2j2hUsGPFFF5agA84Q5&s=2j3QEZN1-m3UtP5LiaS7868XuRq-V6WZoYTsKqSnAnI&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=JwuJ1w2SX8Eq7z2G1vWDTt3xQ39YeafDqhIF06JiDng&m=Pbwy-wH-T_c2Tc6fechV-n_WjtG5BCQS6AMW6yBOmY1xL2j2hUsGPFFF5agA84Q5&s=-4to_C-HCZdB1wWHqr-Xx4vFH09gSv61sQNRCxCc--4&e=>.

**Comment by DataIntellSystLab** [comment]
Hello everyone,

I re-compiled KARGA under openjdk 8, and put the files under openjdk-8/

**Comment by christophevandijck** [comment]
Waw, that's wonderful! Thank you so much for your kind help.
